//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3_MVC_HospitalRecords.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalRecordsDBContext : DbContext
    {
        public HospitalRecordsDBContext()
            : base("name=HospitalRecordsDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DoctorTbl> DoctorTbls { get; set; }
        public DbSet<PatientTbl> PatientTbls { get; set; }
        public DbSet<UserTbl> UserTbls { get; set; }
    }
}
