//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3_MVC_HospitalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTbl
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> docid { get; set; }
        public Nullable<System.DateTime> admission { get; set; }
        public Nullable<System.DateTime> discharge { get; set; }
        public string isdischarge { get; set; }
    
        public virtual DoctorTbl DoctorTbl { get; set; }
    }
}
